GET http://localhost:3000
####
GET http://localhost:3000/routes
#####
GET http://localhost:3000/routes/64e36f9534e9ad0071a79bd5


#####
POST http://localhost:3000/routes
Content-Type: application/json

{
  "name": "rota test",
  "source_id": "ChIJmx-wX0rCpgARjxH_rJ8d5do",
  "destination_id": "ChIJMyzPysqQpgARlznSOl55NVs"
    
}

#####
GET http://localhost:3000/places?text=belo horizonte, mg


####
GET http://localhost:3000/directions?originId=ChIJmx-wX0rCpgARjxH_rJ8d5do&destinationId=ChIJMyzPysqQpgARlznSOl55NVs

