version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - .:/home/node/app
    command: sh -c "npm install && npx prisma generate && npm run start:dev"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      # - "host.docker.internal:172.17.0.1" # docker internal IP


  db:
    build: 
      context: .
      dockerfile: Dockerfile.db
    environment:
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_REPLICA_HOST: db
    volumes:
       - mongodb_data:/data/db

  redis:
    image: redis:7.0.8-alpine
    

volumes:
  mongodb_data:
    driver: local
